services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t spekulant/ubuntu-opencv .
  - docker push spekulant/ubuntu-opencv
